### ISSUE TITLE
`from pwn import *` ValueError: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by ndrewh** [ndrewh/pyda#4]
```
You are running Pyda v0.1.1.
Traceback (most recent call last):
  File "/examples/simple.py", line 5, in <module>
    from pwn import *
  File "/opt/custom-python-root/lib/python3.10/site-packages/pwn/__init__.py", line 6, in <module>
    pwnlib.args.initialize()
  File "/opt/custom-python-root/lib/python3.10/site-packages/pwnlib/args.py", line 209, in initialize
    term.init()
  File "/opt/custom-python-root/lib/python3.10/site-packages/pwnlib/term/__init__.py", line 78, in init
    term.init()
  File "/opt/custom-python-root/lib/python3.10/site-packages/pwnlib/term/term.py", line 110, in init
    signal.signal(signal.SIGWINCH, handler_sigwinch)
  File "/opt/custom-python-root/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

**Comment by ndrewh** [comment]
Can we just export `NOTERM=1` lol? https://github.com/Gallopsled/pwntools/blob/fe560c98355ccfea6f895f64c12eb39d082147ca/pwnlib/args.py#L134
